### ISSUE TITLE
nats: timeout on client.flush

### ISSUE THREAD

**Issue by videlov** [nats-io/nats-pure.rb#40]
We observed a timeout happening on flush with the following stacktrace:

```
nats: timeout
/var/vcap/data/packages/director/f0cf3673bd2c2187b33530f649f1d27a03f4187a/gem_home/ruby/2.6.0/gems/nats-pure-0.6.2/lib/nats/io/client.rb:842:in `with_nats_timeout'
/var/vcap/data/packages/director/f0cf3673bd2c2187b33530f649f1d27a03f4187a/gem_home/ruby/2.6.0/gems/nats-pure-0.6.2/lib/nats/io/client.rb:544:in `block in flush'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/95f13ead566b2d36b0efb94d0377994d7ff5cf3d/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/var/vcap/data/packages/director/f0cf3673bd2c2187b33530f649f1d27a03f4187a/gem_home/ruby/2.6.0/gems/nats-pure-0.6.2/lib/nats/io/client.rb:538:in `flush'
```

What could be the issue here, could a load on the system cause an issue to the ping-pong protocol when flush is used? 

The problem is hard to reproduce, it happens just from time to time and we observed it was when BOSH director was busy updating a lot of deployments. We assume the BOSH VM was under stress during this time. Could the ping-pong thread be affected, or the pong misplaced, not recognised (synchronisation issue?) so that we run into this timeout.

What possible workarounds / fixes we may implement in place to mitigate such an issue.

**Comment by wallyqs** [comment]
Thanks for the report, I need to dig deeper but it looks like it could be a synchronization issue as you mention, since for this to happen it would mean that the pong took over 60 sec timeout to be received.
