### ISSUE TITLE
nats: fetch timeout (NATS::IO::Timeout) when connecting JetStream

### ISSUE THREAD

**Issue by bomu-bomu** [nats-io/nats-pure.rb#70]
I've tried to test nats-pure with Jetstream on  M1 ,  
Using
- Docker nats:latest image  <e4414e480266>  
- nats-pure  2.0.0  on Ruby 3.1.1

And copy code block from example:
```
gem 'nats-pure', '=2.0.0'
require 'nats/client'

nc = NATS.connect
js = nc.jetstream

js.add_stream(name: "mystream", subjects: ["foo"])

js.publish("foo", "Hello JetStream!")

psub = js.pull_subscribe("foo", "bar")

loop do
  msgs = psub.fetch(5)
  msgs.each do |msg|
    msg.ack
  end 
end
```

I found timeout occur
```
/Users/testuser/.rvm/gems/ruby-3.1.1/gems/nats-pure-2.0.0/lib/nats/io/js.rb:629:in `block in fetch': nats: fetch timeout (NATS::IO::Timeout)
	from /Users/testuser/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
	from /Users/testuser/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
	from /Users/testuser/.rvm/gems/ruby-3.1.1/gems/nats-pure-2.0.0/lib/nats/io/js.rb:620:in `fetch'
	from test.rb:14:in `block in <main>'
	from test.rb:13:in `loop'
	from test.rb:13:in `<main>
```

Nats Log with debug display like this:
```
service_1  | [1] 2022/03/24 07:40:18.592069 [DBG] Enabled JetStream for account "$G"
service_1  | [1] 2022/03/24 07:40:18.592071 [DBG]   Max Memory:      -1 B
service_1  | [1] 2022/03/24 07:40:18.592072 [DBG]   Max Storage:     -1 B
service_1  | [1] 2022/03/24 07:40:18.592397 [DBG] JetStream state for account "$G" recovered
service_1  | [1] 2022/03/24 07:40:18.592803 [INF] Listening for client connections on 0.0.0.0:4222
service_1  | [1] 2022/03/24 07:40:18.592817 [DBG] Get non local IPs for "0.0.0.0"
service_1  | [1] 2022/03/24 07:40:18.593015 [DBG]   ip=172.19.0.2
service_1  | [1] 2022/03/24 07:40:18.593024 [INF] Server is ready
service_1  | [1] 2022/03/24 07:40:45.777369 [DBG] 172.19.0.1:56152 - cid:4 - Client connection created
service_1  | [1] 2022/03/24 07:40:48.072274 [DBG] 172.19.0.1:56152 - cid:4 - "v2.0.0:ruby3.1.1" - Client Ping Timer
service_1  | [1] 2022/03/24 07:40:55.828695 [DBG] 172.19.0.1:56152 - cid:4 - "v2.0.0:ruby3.1.1" - Client connection closed: Client Closed
service_1  | [1] 2022/03/24 09:53:44.633139 [DBG] 172.19.0.1:56154 - cid:11 - Client connection created
service_1  | [1] 2022/03/24 09:53:46.700322 [DBG] 172.19.0.1:56154 - cid:11 - "v2.0.0:ruby3.1.1" - Client Ping Timer
service_1  | [1] 2022/03/24 09:53:54.672813 [DBG] 172.19.0.1:56154 - cid:11 - "v2.0.0:ruby3.1.1" - Client connection closed: Client Closed
```
How can I investigate this timeout ??

**Comment by mason-stewart** [comment]
Also encountering this on a M1 Macbook Pro. Nats server is running and otherwise working fine when clients are in Docker/Linux, but getting timeout when running natively on macOS.

**Comment by mason-stewart** [comment]
Apologies for chiming in with what turned out to be unrelated, but just to followup for future readers, my specific issue was an invalid stream name causing a timeout when calling `add_stream`. I opened a PR that was merged to prevent this from happening: https://github.com/nats-io/nats-pure.rb/pull/71

**Comment by wallyqs** [comment]
Fixed example to catch the timeout so that loop retries #93
